### PR TITLE
Add default to fromPackages data field

### PR DESCRIPTION
**Pull request by idanelor**

### CODE REVIEW

**Comment by garethr** [comment]
Thanks for submitting.

This appears to be caused by the fact `from` is required, but also reserved, so we introduced this field. Happy to make this optional.

A better solution to this would be:

 ```python
Optional[List[Any]] = field(default_factory=list)
```

This marks it explicitly as optional, and sets up the default as a list, which makes the API nicer (and consistent with the rest of the models).

This would also presumably want patching at https://github.com/snyk-labs/pysnyk/blob/b0780458029a0d9ee3b5047f45e511811d9de561/snyk/models.py#L44

If you could resubmit I can merge and push a new release.

**Comment by idanelor** [comment]
Thanks @garethr . Done and tested.

**Comment by garethr** [comment]
Apologies, that should have been:

```python
Optional[List[str]] = field(default_factory=list)
```

So as not to change the type.

If you could also add to line 44 as well as referred above then I'll merge and release later today.

**Comment by garethr** [comment]
Fixing in #87

**Pull request closed without merging**
