### PR TITLE
Add support for cloning integrations between orgs

### PR DESCRIPTION
**Pull request by colinbarr**
Added method to allow [cloning integrations](https://snyk.docs.apiary.io/#reference/integrations/integration-cloning/clone-an-integration-(with-settings-and-credentials)) from one organization to another.

### CODE REVIEW

**Review by carwin — APPROVED** [review]
Looks okay to me.

**Comment by colinbarr** [comment]
Thanks @carwin! I've bumped the version to `0.9.4`, since `0.9.3` has since been taken - would you be able to approve again, and merge if you're happy? Thanks.

**Review by garethr — APPROVED** [review]
Apologies for it talking us so long to get back to this PR. Very useful utility function, and thanks for adding the tests too. I'll clear up the version part.

**Comment by colinbarr** [comment]
Great, thank you @garethr!

**Pull request merged**
